apiVersion: v1
kind: Service
metadata:
  name: nginxjsdemo
  labels:
    name: app
    app: nginxjs
spec:
  ports:
    - name: nginxjs
      port: 80
      targetPort: 80
  selector:
    name: app
    app: nginxjs
    color: blue
  type: LoadBalancer
